Web branch
Chike1990/cloned_NYT pull request #2
Opened 2021-02-25 16:31 UTC by Chike1990

I cloned an article page of the New York Times applying the concepts I learned over the week. Specifically,
I first created a repository on Github, created a branch from it, added ReadMe file, added linter checks, index.html file, and style.css file.
The structure and content of the New York Times article page were laid out in HTML- using HTML 5 semantic tags; the images were downloaded from the NYT page and were included in the cloned web page; these contents were style using CSS - and by applying concepts like positioning, flex, float, etc.
In other words, this page includes a navbar, an aside, main, sections, articles, divs, footer, etc. Prior to sending a pull request, linters were checked for errors in the style and index files and about five code reviewers reviewed this code and made recommendations that have been included.

2021-02-25 18:47 UTC, wathigo requested changes
## CHANGES REQUIRED :o:  
Great job on this project.
Semantic HTML has been used throughout the page.
Let's fix one issue before we proceed.

### REQUIRED
The bottom part of the page containing more articles is missing. See this :point_down: 
Original Page | Cloned Page
|-------------------|------------------|
![Screenshot from 2021-02-25 13-33-03](https://user-images.githubusercontent.com/44072711/109201345-bc59a980-776f-11eb-9bf5-c51f47e2a991.png) | ![Screenshot from 2021-02-25 13-44-36](https://user-images.githubusercontent.com/44072711/109201403-cc718900-776f-11eb-9fd5-4c6b5dbf6992.png)

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

2021-02-25 18:56 UTC, Chike1990 commented
Alright, thank you

Regards,
Chibuike

On Thu, Feb 25, 2021, 7:47 PM Simon Wathigo <notifications@github.com>
wrote:

> *@wathigo* requested changes on this pull request.
> CHANGES REQUIRED ⭕
>
> Great job on this project.
> Semantic HTML has been used throughout the page.
> Let's fix one issue before we proceed.
> REQUIRED
>
> The bottom part of the page containing more articles is missing. See this
> 👇
> Original Page Cloned Page
> [image: Screenshot from 2021-02-25 13-33-03]
> <https://user-images.githubusercontent.com/44072711/109201345-bc59a980-776f-11eb-9bf5-c51f47e2a991.png> [image:
> Screenshot from 2021-02-25 13-44-36]
> <https://user-images.githubusercontent.com/44072711/109201403-cc718900-776f-11eb-9fd5-4c6b5dbf6992.png>
>
> *After making the changes, submit another request for review.*
>
>
> *Happy Coding 💻 Simon Wathigo*
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Chike1990/cloned_NYT/pull/2#pullrequestreview-598891523>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO2A5OCFSCO5UO2P767FYATTA2LNPANCNFSM4YG2CA3A>
> .
>

2021-02-26 21:54 UTC, Chike1990 commented
I cloned an article page of the New York Times applying the concepts I learned over the week. Specifically,
I first created a repository on Github, created a branch from it, added ReadMe file, added linter checks, index.html file, and style.css file.
The structure and content of the New York Times article page were laid out in HTML- using HTML 5 semantic tags; the images were downloaded from the NYT page and were included in the cloned web page; these contents were style using CSS - and by applying concepts like positioning, flex, float, etc.
In other words, this page includes a navbar, an aside, main, sections, articles, divs, footer, etc. Prior to sending a pull request, linters were checked for errors in the style and index files and about five code reviewers reviewed this code and made recommendations that have been included.

2021-02-27 09:47 UTC, teekaytech requested changes
### Status: Changes Required :warning: :vertical_traffic_light: 

**Hello @Chike1990  :wave:**

__Thank you for implementing the changes highlighted by the last reviewer.__

**Major highlights:**
- You did well to add the fixed footer at the bottom of the page :+1: 
- Your webpage looks good: you paid attention to the details :ok: 
- Nice implementation of theTheory of Inflation` section :1st_place_medal: 
- All linter checks are running successfully! :100: 

__However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] The project screenshot is not rendering on your Readme. Kindly look into this. This [stack overflow thread](https://stackoverflow.com/questions/14494747/how-to-add-images-to-readme-md-on-github) might help.
- [ ] The `Issues page` and `MIT license` links on your Readme are broken. Kindly [add the license file](https://stackoverflow.com/questions/31639059/how-to-add-license-to-an-existing-github-project) to your project and ensures that all links lead to the correct pages. 

**[ OPTIONAL CHANGES ]**
_**Note: the highlighted changes in this category are not compulsory: your project will be approved if they're not implemented. However, you're advised to make these changes so as to develop a more professional project.**_
- [ ] I observed that you added the `SVG` image tags directly in your HTML file. This will work, but when it becomes too much, it tends to mess up your HTML file. Instead, you can create separate files for individual SVG images, then use the image tag to reference them in your HTML file. [This article](https://www.freecodecamp.org/news/use-svg-images-in-css-html/) might help.

**That's it!**
* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-02-27 10:35 UTC, Chike1990 commented
I cloned an article page of the New York Times applying the concepts I learned over the week. Specifically,
I first created a repository on Github, created a branch from it, added ReadMe file, added linter checks, index.html file, and style.css file.
The structure and content of the New York Times article page were laid out in HTML- using HTML 5 semantic tags; the images were downloaded from the NYT page and were included in the cloned web page; these contents were style using CSS - and by applying concepts like positioning, flex, float, etc.
In other words, this page includes a navbar, an aside, main, sections, articles, divs, footer, etc. Prior to sending a pull request, linters were checked for errors in the style and index files and about five code reviewers reviewed this code and made recommendations that have been included.

2021-02-27 11:34 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Chike1990 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes 👇.
- [ ] The project screenshot is not rendering on your Readme. Kindly fix this issue as the previous TSE explained. See the Hit in comment
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-02-27 11:34 UTC, umairarshadbutt commented on README.md
> +![screenshot](Assets\ProjectScreenShot.jpg)
The image path is wrong, please fix it. You can update from `![screenshot](Assets\ProjectScreenShot.jpg)` to `![screenshot](Assets/ProjectScreenShot.jpg)`

2021-02-27 12:54 UTC, Chike1990 commented
I cloned an article page of the New York Times applying the concepts I learned over the week. Specifically,
I first created a repository on Github, created a branch from it, added ReadMe file, added linter checks, index.html file, and style.css file.
The structure and content of the New York Times article page were laid out in HTML- using HTML 5 semantic tags; the images were downloaded from the NYT page and were included in the cloned web page; these contents were style using CSS - and by applying concepts like positioning, flex, float, etc.
In other words, this page includes a navbar, an aside, main, sections, articles, divs, footer, etc. Prior to sending a pull request, linters were checked for errors in the style and index files and about five code reviewers reviewed this code and made recommendations that have been included.

2021-02-27 13:46 UTC, enaburekhan requested changes
# Status: Required changes:full_moon:
**Hi Chibuike!
Many thanks for implementing the changes requested by the previous reviewers:clap::clap:. The UI is awesome and the cloned website looks very much like the original:100:. Keep up the good job:thumbsup:.
We just need to make an adjustment to that same screen-shot in the readme to get this project approved:muscle:.** 

- [ ] The current screen-shot is good but not good enough to be featured in the readme of a project. check my [screen-shot](https://imgur.com/a/R2EDvEI) from the same cloned project. Use something similar or better.

Make the above-required change and when you are ready, request another review.
Kindly drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking
Eric Enaburekhan

2021-02-27 14:39 UTC, Chike1990 commented
I cloned an article page of the New York Times applying the concepts I learned over the week. Specifically,
I first created a repository on Github, created a branch from it, added ReadMe file, added linter checks, index.html file, and style.css file.
The structure and content of the New York Times article page were laid out in HTML- using HTML 5 semantic tags; the images were downloaded from the NYT page and were included in the cloned web page; these contents were style using CSS - and by applying concepts like positioning, flex, float, etc.
In other words, this page includes a navbar, an aside, main, sections, articles, divs, footer, etc. Prior to sending a pull request, linters were checked for errors in the style and index files and about five code reviewers reviewed this code and made recommendations that have been included.

2021-02-27 15:05 UTC, oloomoses approved these changes
# Congratulation, Project Approved! :tada: :clap: :muscle: 
You have done a great job implementing the changes from the previous review. 
The project is complete and meets all the requirements. Congratulation once again.
You can now merge and close this pull request. Don't forget to submit the completion form after.
I wish you the best in your next project and see you at the top :rocket: 
### Happy coding.
_Slack: Oloo Moses_

2021-02-27 15:09 UTC, Chike1990 commented
[Sighs] 
Let me go take a cool drink😊 

Thanks,

Chike
From: Oloo Moses
Sent: Saturday, February 27, 2021 4:05 PM
To: Chike1990/cloned_NYT
Cc: Chike1990; Mention
Subject: Re: [Chike1990/cloned_NYT] Web branch (#2)

@oloomoses approved this pull request.
Congratulation, Project Approved! 🎉 👏 💪
You have done a great job implementing the changes from the previous review.
The project is complete and meets all the requirements. Congratulation once again.
You can now merge and close this pull request. Don't forget to submit the completion form after.
I wish you the best in your next project and see you at the top 🚀
Happy coding.
Slack: Oloo Moses
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-02-27 15:12 UTC, Chike1990 commented
Complete project

2021-02-27 15:12 UTC, merged